spring:
  application:
    name: CheckingSpringData
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url:
      jdbc:postgresql://localhost:5432/studentcourse
    username: postgres
    password: qwerty12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/main-changelog.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
#  jackson:
#    serialization:
#      fail-on-empty-beans: false